#!/usr/bin/env node
// Generate functions/api/_wiki-gen.ts from src/content/wiki/*.md
// This file is imported by chat-wiki.ts instead of ?raw imports,
// because wrangler's esbuild bundler doesn't support Vite's ?raw suffix.
// Run before: build, dev, test, wrangler pages dev.

const fs = require('fs');
const path = require('path');

const wikiDir = path.join(process.cwd(), 'src', 'content', 'wiki');
const outFile = path.join(process.cwd(), 'functions', 'api', '_wiki-gen.ts');

if (!fs.existsSync(wikiDir)) {
  console.error('ERROR: src/content/wiki/ not found');
  process.exit(1);
}

const files = fs.readdirSync(wikiDir).filter(f => f.endsWith('.md')).sort();

if (files.length === 0) {
  console.error('ERROR: no .md files in src/content/wiki/');
  process.exit(1);
}

let code = '// AUTO-GENERATED by scripts/gen-wiki.cjs — DO NOT EDIT\n';
code += '// Wiki markdown content inlined as string constants for Pages Function.\n';
code += '// Regenerated on every build/dev/test. Not committed to git.\n\n';
code += 'export interface WikiDoc { name: string; md: string; }\n';
code += 'export const WIKI_FILES: WikiDoc[] = [\n';

for (const file of files) {
  const name = file.replace(/\.md$/, '');
  const content = fs.readFileSync(path.join(wikiDir, file), 'utf8');
  // Escape backticks and ${ for template literal safety
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  code += `  { name: '${name}', md: \`${escaped}\` },\n`;
}

code += '];\n';

fs.writeFileSync(outFile, code, 'utf8');
console.log(`Generated functions/api/_wiki-gen.ts (${files.length} wiki files: ${files.map(f => f.replace(/\.md$/, '')).join(', ')})`);
